---
title: "About this Data"
output: html_document
---

## Title IX
> This project tracks federal investigations of colleges for possible violations of the gender-equity law Title IX involving alleged sexual violence. It includes all investigations in this wave of enforcement: those either open now or resolved since April 4, 2011, when the U.S. Department of Education’s Office for Civil Rights issued a “Dear Colleague” letter exhorting colleges to resolve students’ reports of sexual assault — and to protect them throughout the process.([The Chronicle of Higher Education](https://projects.chronicle.com/titleix/))

**More about this dataset:**

## Campus Safety and Security
> This data includes all data submitted through the Campus Safety and Security Survey during each year. The Campus Safety and Security Data is collected by the U.S Department of Education. It aims to assist schools to provide students a safe environment to study and to keep students, parents and employees well informed about campus security.([Campus Safety and Security](https://ope.ed.gov/campussafety/#/))   

**More about this dataset:** This dataset is drawn from the OPE Campus Safety and Security Statistics website database to crime and fire statistics of 2010 data collection, which are submitted annually by web-based data collection. 

## Mishandled Dataset


#### Datasets download links:  
- [Title IX Sexual Assault Tracker API documentation](https://projects.chronicle.com/titleix/api/v1/docs/)   
- [Campus Safety and Security Dataset](https://ope.ed.gov/campussafety/#/datafile/list)