---
title: "Data Report"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning=FALSE}
library(dplyr)
library(knitr)
library(ggplot2)
library(jsonlite)
library(kableExtra)


df <- read.csv("./data/report.data.csv", stringsAsFactors = FALSE)
df <- df[complete.cases(df[,33:41]),]

# confirming rows are formatted properly
df$rape.rate7 <- as.numeric(df$rape.rate7)
df$rape.rate8 <- as.numeric(df$rape.rate8)
df$rape.rate9 <- as.numeric(df$rape.rate9)
df$rape.rate10 <- as.numeric(df$rape.rate10)
df$rape.rate11 <- as.numeric(df$rape.rate11)
df$rape.rate12 <- as.numeric(df$rape.rate12)
df$rape.rate13 <- as.numeric(df$rape.rate13)
df$rape.rate14 <- as.numeric(df$rape.rate14)
df$rape.rate15 <- as.numeric(df$rape.rate15)

# calculating mean rape rates
means <- c(mean(df$rape.rate7),
           mean(df$rape.rate8),
           mean(df$rape.rate9), 
           mean(df$rape.rate10),
           mean(df$rape.rate11), 
           mean(df$rape.rate12), 
           mean(df$rape.rate13), 
           mean(df$rape.rate14), 
           mean(df$rape.rate15))
means <- round(means, 3)

years <- c('2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015')

# combining for graph data
medians.data <- as.data.frame(cbind(means, years))

# adding mean graph
ggplot(data = medians.data, aes(
  x = years,
  y = means,
  group = 1
)) + 
  geom_line() + 
  ggtitle("Mean # of Reported Rape Cases per Year")

# getting the campuses with the most assault
maxes <- c(max(df$rape.rate7),
           max(df$rape.rate8),
           max(df$rape.rate9), 
           max(df$rape.rate10),
           max(df$rape.rate11), 
           max(df$rape.rate12), 
           max(df$rape.rate13), 
           max(df$rape.rate14), 
           max(df$rape.rate15)
)
maxes <- round(maxes, 3)

# getting campus names
campuses <- c(df %>% filter(rape.rate7 == max(df$rape.rate7)) %>%  select(INSTNM),
           df %>% filter(rape.rate8 == max(df$rape.rate8)) %>% select(INSTNM),
           df %>% filter(rape.rate9 == max(df$rape.rate9)) %>% select(INSTNM), 
           df %>% filter(rape.rate10 == max(df$rape.rate10)) %>% select(INSTNM),
           df %>% filter(rape.rate11 == max(df$rape.rate11)) %>% select(INSTNM), 
           df %>% filter(rape.rate12 == max(df$rape.rate12)) %>% select(INSTNM), 
           df %>% filter(rape.rate13 == max(df$rape.rate13)) %>% select(INSTNM), 
           df %>% filter(rape.rate14 == max(df$rape.rate14)) %>% select(INSTNM), 
           df %>% filter(rape.rate15 == max(df$rape.rate15)) %>% select(INSTNM)
)

# combining for one table
max.data <- as.data.frame(cbind(campuses, maxes, years))


# adding table of maxes
kable(max.data, row.names = FALSE)



# Read the title.ix data.
title.ix.data <- read.csv('./data/title.ix.cases.csv', stringsAsFactors = FALSE)
# Read closed case data
close <- title.ix.data %>% filter(is.closed == "TRUE") %>% select(case_id, opened, closed)
# Set the open date int othe form that is usable
closed.case.open.date <- as.Date(close$opened, format = "%m/%d/%y")
# Set the close date int othe form that is usable
closed.case.close.date <- as.Date(close$closed, format = "%m/%d/%y")
# Calculate the days that take for each closed case.
duration <- closed.case.close.date - closed.case.open.date
average.duration <- round(sum (duration) / nrow(as.data.frame(duration)), digits = 1)
# Calculate mishandled/open cases.
open.cases <- title.ix.data %>% filter(is.closed == "FALSE")
num.open.cases <- nrow(open.cases)
```

The above table reports the campus with the most rapes per 1000 students over each year of data.

1. Aside from a few outliers, the rate of reported campus rape has been slowly increasing. However, because only an estimated 2% of rapes are reported, it's unclear whether this increase correlates to a genuine increase in rape cases or an increase in its reporting. This could easily be due to different survey techniques across years.
2. Several campuses (Mayo Medical School, Shimer College) appear on the list of worst offenders multiple times.
3. The average days it take for colleges tend to close reported cases is `r average.duration` days.  
4. There are `r num.open.cases` mishandled cases from 2010 to 2016. 
5. The time it takes to close a case is steadily decreasing with time.

